### ISSUE TITLE
[PE-D][Tester A] adding appointment is missing the 2 divisor lines

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113T-T09-4/tp#180]
When adding an appointment, the output I get is this

![image.png](https://raw.githubusercontent.com/Fureimi/ped/main/files/047252de-3473-4478-ae35-adb65f36410a.png)

which is missing the 2 divisor lines on your UG:

![image.png](https://raw.githubusercontent.com/Fureimi/ped/main/files/d131f434-c261-485c-8558-30fa4fe6a88b.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Fureimi/ped#5

**Comment by rouvinerh** [comment]
Added.
