### ISSUE TITLE
[PE-D][Tester C] Station name of gym workouts cut short by /

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-4/tp#183]
If a backslash character (/) is present in the station name of a gym workout, the rest of the name after the backslash will not be recorded

![image.png](https://raw.githubusercontent.com/JianJiaT/ped/main/files/795857c5-f29e-48aa-86f3-5a66e3131c42.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: JianJiaT/ped#10

**Comment by rouvinerh** [comment]
Fixed in issue #189 by limiting number of '/' that can be entered.
@JustinSoh for your ref
