### ISSUE TITLE
[PE-D][Tester B] heath BMI

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-4/tp#187]
I think the error messages could be more tailored to the error made:

![image.png](https://raw.githubusercontent.com/HiteshriAcharya/ped/main/files/e10f8326-703d-4ce5-b65e-9084b08c949e.png)

for example for this, i took some time to realise it was the spacing that was causing the issue and not exactly insufficient number of input

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: HiteshriAcharya/ped#6

**Comment by syj02** [comment]
Fixed.

Instructions added in the UG  under **`Notes about command format`** and **`FAQs`** question 7 to highlight to users the risks of getting errors thrown due to extra and/or missing characters in the commands.
