### ISSUE TITLE
[PE-D][Tester C] Description of health appointments cut short by /

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113T-T09-4/tp#189]
If the user inputs a backslash character (/) in the description of a health appointment, the remainder of the description after the backslash will not be recorded

![image.png](https://raw.githubusercontent.com/JianJiaT/ped/main/files/b20b1d07-9dc7-441d-8af3-cc54cffcd22a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: JianJiaT/ped#11

**Comment by rouvinerh** [comment]
Added check for all inputs for the number of '/' entered. Parameters cannot have '/' within them.
