### ISSUE TITLE
[PE-D][Tester D] Faulty Rendering of User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113T-T09-4/tp#202]
![image.png](https://raw.githubusercontent.com/ShyamKrishna33/ped/main/files/4160da06-1c32-471f-a473-001f7896472a.png)

The brackets '{}' are visible in the output.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ShyamKrishna33/ped#6

**Comment by rouvinerh** [comment]
Removed.
